CREATE TABLE users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    enabled    BOOLEAN      NOT NULL,
    full_name  VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    user_name  VARCHAR(255) NOT NULL UNIQUE,

    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'USER'))
);


CREATE TABLE customers
(
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address       VARCHAR(255),
    city          VARCHAR(255),
    country       VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    deleted       BOOLEAN      NOT NULL,
    email         VARCHAR(255),
    industry      VARCHAR(255) NOT NULL,
    phone         VARCHAR(255),
    status        VARCHAR(255) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    website       VARCHAR(255),

    created_by    BIGINT       NOT NULL,
    updated_by    BIGINT,

    CONSTRAINT customers_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'LEAD')),

    CONSTRAINT fk_customer_created_by FOREIGN KEY (created_by) REFERENCES users (user_id),

    CONSTRAINT fk_customer_updated_by FOREIGN KEY (updated_by) REFERENCES users (user_id)
);


CREATE TABLE contacts
(
    contact_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    deleted     BOOLEAN      NOT NULL,
    email       VARCHAR(255),
    first_name  VARCHAR(255) NOT NULL,
    job_title   VARCHAR(255),
    last_name   VARCHAR(255) NOT NULL,
    phone       VARCHAR(255),
    updated_at  TIMESTAMP(6) NOT NULL,

    customer_id BIGINT       NOT NULL,

    CONSTRAINT fk_contact_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);


CREATE TABLE notes
(
    note_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    note_text   TEXT         NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,

    created_by  BIGINT       NOT NULL,
    customer_id BIGINT       NOT NULL,
    updated_by  BIGINT,
    deleted     BOOLEAN      NOT NULL,

    CONSTRAINT fk_note_created_by FOREIGN KEY (created_by) REFERENCES users (user_id),

    CONSTRAINT fk_note_updated_by FOREIGN KEY (updated_by) REFERENCES users (user_id),

    CONSTRAINT fk_note_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);


CREATE TABLE user_credentials
(
    credential_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_user_credentials_user FOREIGN KEY (user_id) REFERENCES users (user_id),

    CONSTRAINT uq_user_credentials_user UNIQUE (user_id)
);